[package]
name = "sample_planets"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
artificer_assets = { workspace = true }
artificer_input = { workspace = true }
artificer_procgen = { workspace = true }
artificer_render = { workspace = true }
artificer_scene = { workspace = true }
glam = { workspace = true }
